language: node_js
node_js:
- 5.11.0
before_script:
- npm install
after_script:
- npm test
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha tests/**.test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
