language: node_js
node_js:
- 5.11.0
before_script:
- npm install
after_script:
- npm test
after_success:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
